/* Autogenerated by png2wx.pl on Thu Nov  4 13:06:52 2010 */
#ifndef ICONS_H
#define ICONS_H 1

#include <wx/wxprec.h>
#ifndef WX_PRECOMP
#	include <wx/wx.h>
#endif

extern void initialize_images(void);

extern wxBitmap *_img_frcurrents_pi;
extern wxBitmap *_img_frcurrents;
extern wxBitmap *_img_Clock;

#ifdef ocpnUSE_SVG
extern wxString _svg_frcurrents;
extern wxString _svg_frcurrents_rollover;
extern wxString _svg_frcurrents_toggled;
#endif


#endif /* ICONS_H */
